// <auto-generated />
using System;
using GestionStock.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionStock.Api.Migrations
{
    [DbContext(typeof(GestionStockDbContext))]
    [Migration("20260826121456_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionStock.Shared.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryArticleId")
                        .HasColumnType("int");

                    b.Property<string>("CodeBarre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("StockActuel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryArticleId");

                    b.HasIndex("CodeBarre");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.CategoryArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CategoryArticles");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.CategoryOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryOperations");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.DetailOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Emplacement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarque")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("OperationId");

                    b.ToTable("DetailOperations");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryOperationId")
                        .HasColumnType("int");

                    b.Property<string>("Ch01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch07")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch08")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch09")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ch10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreePar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOperation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<int?>("IdParentOperation")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifieLe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryOperationId");

                    b.HasIndex("CreePar");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("IdParentOperation");

                    b.HasIndex("ModifiePar");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.Article", b =>
                {
                    b.HasOne("GestionStock.Shared.Entities.CategoryArticle", "CategoryArticle")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoryArticle");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.CategoryArticle", b =>
                {
                    b.HasOne("GestionStock.Shared.Entities.CategoryArticle", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.DetailOperation", b =>
                {
                    b.HasOne("GestionStock.Shared.Entities.Article", "Article")
                        .WithMany("DetailOperations")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionStock.Shared.Entities.Operation", "Operation")
                        .WithMany("DetailOperations")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.Operation", b =>
                {
                    b.HasOne("GestionStock.Shared.Entities.CategoryOperation", "CategoryOperation")
                        .WithMany("Operations")
                        .HasForeignKey("CategoryOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionStock.Shared.Entities.ApplicationUser", "CreeParUser")
                        .WithMany("OperationsCreees")
                        .HasForeignKey("CreePar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionStock.Shared.Entities.Fournisseur", "Fournisseur")
                        .WithMany("Operations")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionStock.Shared.Entities.Operation", "OperationParent")
                        .WithMany("SousOperations")
                        .HasForeignKey("IdParentOperation")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionStock.Shared.Entities.ApplicationUser", "ModifieParUser")
                        .WithMany("OperationsModifiees")
                        .HasForeignKey("ModifiePar")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoryOperation");

                    b.Navigation("CreeParUser");

                    b.Navigation("Fournisseur");

                    b.Navigation("ModifieParUser");

                    b.Navigation("OperationParent");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.ApplicationUser", b =>
                {
                    b.Navigation("OperationsCreees");

                    b.Navigation("OperationsModifiees");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.Article", b =>
                {
                    b.Navigation("DetailOperations");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.CategoryArticle", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Enfants");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.CategoryOperation", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.Fournisseur", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("GestionStock.Shared.Entities.Operation", b =>
                {
                    b.Navigation("DetailOperations");

                    b.Navigation("SousOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
